name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  PATH_PROJECT: ./Groffe.Distancias/Groffe.Distancias.csproj
  PATH_TESTS_PROJECT: ./Groffe.Distancias.Testes/Groffe.Distancias.Testes.csproj
  TEST_RESULTS_DIRECTORY: ./TestResults
  TEST_RESULTS_FILE: ./TestResults/resultado-testes.xml

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.201
    - name: Execução dos testes
      run: dotnet test ${{ env.PATH_TESTS_PROJECT }} --results-directory ${{ env.TEST_RESULTS_DIRECTORY }} --logger:"trx;LogFileName=resultado-testes.trx"
    - name: Exibir resultado da execução dos testes com xUnit
      if: always()
      run: |
        ls
        echo "Conteúdo do diretório ${{ env.TEST_RESULTS_DIRECTORY }}"
        cd ${{ env.TEST_RESULTS_DIRECTORY }}
        ls
        cat resultado-testes.trx
    - name: Instalar a Global Tool dotnet-xunit-to-junit
      if: always()
      run: dotnet tool install --global dotnet-xunit-to-junit --version 4.0.0
    - name: Exibir resultado da execução dos testes com xUnit
      if: always()
      run: |
        echo "Conteúdo do diretório ${{ env.TEST_RESULTS_DIRECTORY }}"
        cd ${{ env.TEST_RESULTS_DIRECTORY }}
        ls
        cat resultado-testes.trx
    - name: Converter XML com resultado da execução dos testes com xUnit para formato do JUnit
      if: always()
      run: |
        cd ${{ env.TEST_RESULTS_DIRECTORY }}
        dotnet xunit-to-junit "resultado-testes.trx" "resultado-testes.xml"
        ls
        cat resultado-testes.xml
    - name: Criar Test Summary
      uses: test-summary/action@dist
      with:
        paths: ${{ env.TEST_RESULTS_FILE }}
      if: always()
