name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  PATH_PROJECT: ./Groffe.Distancias/Groffe.Distancias.csproj
  PATH_TESTS_PROJECT: ./Groffe.Distancias.Testes/Groffe.Distancias.Testes.csproj
  TEST_RESULTS_DIRECTORY: ./TestResults
  TEST_RESULTS_FILE: ./TestResults/resultado-testes.xml

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.201
    - name: Configurar package JUnit
      run: |
        cd ./Groffe.Distancias.Testes
        dotnet add package JunitXml.TestLogger --version 3.0.110
    - name: Execução dos testes
      run: dotnet test ${{ env.PATH_TESTS_PROJECT }} --results-directory ${{ env.TEST_RESULTS_DIRECTORY }} --logger:"junit;LogFileName=resultado-testes.xml"
    - name: Exibir resultado da execução dos testes com xUnit já convertido para JUnit
      if: always()
      run: |
        echo "Conteúdo do diretório ${{ env.TEST_RESULTS_DIRECTORY }}"
        cd ${{ env.TEST_RESULTS_DIRECTORY }}
        ls
        cat resultado-testes.xml
    - name: Criar Test Summary
      uses: test-summary/action@v1.0
      with:
        paths: ${{ env.TEST_RESULTS_FILE }}
      if: always()
